spring:
  profiles:
    active: dev
---
 spring:
   profiles: dev
   application:
     name: springcloud-config-dev-mark
---
 spring:
   profiles: test
   application:
     name: springcloud-config-test-mark