spring:
  profiles:
    active: dev
---
spring:
  profiles: test
  application:
    name: lian-note-users
server:
  port: 8201
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/,http://eureka03.com:7003/eureka/
  instance:
    instance-id: lian-note-users-hystrix-8001
    prefer-ip-address: true
---
spring:
  profiles: dev
  application:
    name: lian-note-users
server:
  port: 8202
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/,http://eureka03.com:7003/eureka/
  instance:
    instance-id: lian-note-users-hystrix-8001
    prefer-ip-address: true
