spring:
  profiles:
    active: dev
---
logging:
#  config: classpath:logback-spring.xml
  level:
    xyz.lian1998: ERROR
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] %-5level - %msg%n"
  file:
    path: "C:/MyLogging/lian-note-users"
    clean-history-on-start: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  type-aliases-package: xyz.lian1998.pojo

spring:
  profiles: dev
  application:
    name: lian-note-users
  datasource:
    schema:
      - classpath:sql/lian-note-users.sql
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8201

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/,http://eureka03.com:7003/eureka/
  instance:
    instance-id: lian-note-users-8001
    # 这是在 eureka 中, 此进程服务的名字
    # spring.application.name 内的值, 是该类进程(该模块进程的总名字)
    prefer-ip-address: true   # 在链接到 进程实例详细信息 链接时候显示进程所在服务器ip

info:
  app.name: lian-note-users
  company.name: www.lian1998.xyz
  build.artifactId: %project.artifactId%
  build.version: %project.version%
 ---
 logging:
#  config: classpath:logback-spring.xml
  level:
    xyz.lian1998: ERROR
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] %-5level - %msg%n"
  file:
    path: "C:/MyLogging/lian-note-users"
    clean-history-on-start: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  type-aliases-package: xyz.lian1998.pojo

spring:
  profiles: test
  application:
    name: lian-note-users
  datasource:
    schema:
      - classpath:sql/lian-note-users.sql
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8202

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/,http://eureka03.com:7003/eureka/
  instance:
    instance-id: lian-note-users-8001
    # 这是在 eureka 中, 此进程服务的名字
    # spring.application.name 内的值, 是该类进程(该模块进程的总名字)
    prefer-ip-address: true   # 在链接到 进程实例详细信息 链接时候显示进程所在服务器ip

info:
  app.name: lian-note-users
  company.name: www.lian1998.xyz
  build.artifactId: %project.artifactId%
  build.version: %project.version%